---
- name: "Add node.js from source"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
- name: "Install node.js 14"
  become: true
  apt:
    name: ["nodejs"]
    state: present
    update_cache: yes

- name: "Install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes

- name: "move env variables to /etc/profile.d"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/